name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  path: ^1.8.2
  image_picker: ^1.1.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  provider: ^6.1.1
  flutterfire_cli: ^1.1.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
