// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqu0NnpJynJRROWJX0h15wRTOfjBvymFU',
    appId: '1:781740763356:android:29320453dc036e1260ec19',
    messagingSenderId: '781740763356',
    projectId: 'ecommerceu24',
    storageBucket: 'ecommerceu24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqHFjEireGu-SVHlXJT0--aMIi41wzfd0',
    appId: '1:781740763356:ios:b8f245c927b1368a60ec19',
    messagingSenderId: '781740763356',
    projectId: 'ecommerceu24',
    storageBucket: 'ecommerceu24.firebasestorage.app',
    androidClientId: '781740763356-5nrlvt0p0693sh6edaftktqi91bl076v.apps.googleusercontent.com',
    iosClientId: '781740763356-u028bvbf3k4vdsn5pjprkas0ug6avkec.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallery',
  );
}
